### ISSUE TITLE
New words: technical debt

### ISSUE THREAD

**Issue by arrested-developer** [dwyl/technical-glossary#10]
- [x] add definition for technical debt

https://en.wikipedia.org/wiki/Technical_debt

**Comment by Cleop** [comment]
**[Technical Debt](https://en.wikipedia.org/wiki/Technical_debt)** - Technical debt is the time/cost of "re-working" a feature (or entire app) because corners were cut the first time it was built. Think of Technical Debt like a "loan shark" for your project, if you take "shortcuts" to implement a feature quickly (e.g: by skipping tests) you will pay for it later and usually with "interest". For a fuller definition see: https://github.com/dwyl/product-owner-guide#what-is-technical-debt

**Comment by Cleop** [comment]
@arrested-developer - if you are happy with the definition that's been added please close this issue 😊

**Comment by nelsonic** [comment]
https://medium.com/@erichiggins/technical-debt-is-like-tetris-168f64d8b700
